// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlmcBVeUCrV_EmQy4L2z06JmgXER3Svhc',
    appId: '1:896404526861:web:e3481aa84c54c66aedc244',
    messagingSenderId: '896404526861',
    projectId: 'en-parche',
    authDomain: 'en-parche.firebaseapp.com',
    storageBucket: 'en-parche.appspot.com',
    measurementId: 'G-SQ93SX1SF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqEM5P4p1J8X1w1Mvk9xuLxhEEmKdlhKw',
    appId: '1:896404526861:android:7470548dae3da6c8edc244',
    messagingSenderId: '896404526861',
    projectId: 'en-parche',
    storageBucket: 'en-parche.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJOUWJ96icLhYV71xzAPivG-rjoYtOr0k',
    appId: '1:896404526861:ios:71b34fc80f1ac9e0edc244',
    messagingSenderId: '896404526861',
    projectId: 'en-parche',
    storageBucket: 'en-parche.appspot.com',
    iosClientId: '896404526861-1v95fb2e4r3qafoqfjmsegdqoiqispng.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJOUWJ96icLhYV71xzAPivG-rjoYtOr0k',
    appId: '1:896404526861:ios:71b34fc80f1ac9e0edc244',
    messagingSenderId: '896404526861',
    projectId: 'en-parche',
    storageBucket: 'en-parche.appspot.com',
    iosClientId: '896404526861-1v95fb2e4r3qafoqfjmsegdqoiqispng.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
